# modules/pdf_report.py

"""
PDF Executive Report generator for SpoofyVibe.

Generates a branded, multi-page PDF with:
  - Cover page with branding and scan metadata
  - Executive summary with grade distribution and key stats
  - Per-domain score breakdowns with visual bars
  - Domain detail sections with key DNS records
  - Prioritised remediation recommendations

Uses fpdf2 (pure Python, no system dependencies).
"""

import os
from datetime import datetime
from fpdf import FPDF


def _safe(text):
    """Sanitise text for Helvetica (Latin-1 only).

    Replaces common Unicode characters with ASCII equivalents so the PDF
    renderer doesn't crash on unsupported glyphs.
    """
    if not isinstance(text, str):
        text = str(text) if text is not None else ""
    replacements = {
        "\u2014": "-",   # em-dash
        "\u2013": "-",   # en-dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "*",   # bullet
        "\u2026": "...", # ellipsis
        "\u00a0": " ",   # non-breaking space
        "\u2192": "->",  # right arrow
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Strip any remaining non-Latin-1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")

# ── Colour palette (matching dashboard) ──────────────────────────────────────

DARK_BG = (15, 15, 26)
CARD_BG = (26, 26, 46)
ACCENT_INDIGO = (99, 102, 241)
ACCENT_CYAN = (6, 182, 212)
TEXT_PRIMARY = (237, 237, 237)
TEXT_SECONDARY = (160, 160, 180)
TEXT_MUTED = (110, 110, 130)
BORDER_COLOR = (50, 50, 70)

GRADE_COLORS = {
    "A+": (16, 185, 129), "A": (16, 185, 129),
    "B+": (52, 211, 153), "B": (132, 204, 22),
    "C+": (234, 179, 8),  "C": (245, 158, 11),
    "D": (249, 115, 22),  "F": (239, 68, 68),
    "?": (110, 110, 130),
}

PRIORITY_COLORS = {
    1: (239, 68, 68),    # Critical
    2: (249, 115, 22),   # High
    3: (234, 179, 8),    # Medium
    4: (99, 102, 241),   # Low
    5: (110, 110, 130),  # Info
}

PRIORITY_LABELS = {1: "CRITICAL", 2: "HIGH", 3: "MEDIUM", 4: "LOW", 5: "INFO"}

CATEGORY_LABELS = [
    ("spf", "SPF", 20),
    ("dmarc", "DMARC", 20),
    ("dkim", "DKIM", 15),
    ("bimi", "BIMI", 5),
    ("spoofability", "Spoofability", 15),
    ("mta_sts", "MTA-STS", 10),
    ("mx", "MX", 10),
    ("dnssec", "DNSSEC", 5),
]


class PDFReport(FPDF):
    """Custom PDF class with SpoofyVibe branding."""

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(15, 15, 15)

    def header(self):
        """Branded header bar on every page (except cover)."""
        if self.page_no() == 1:
            return
        # Dark header strip
        self.set_fill_color(*DARK_BG)
        self.rect(0, 0, 210, 14, "F")
        # Accent gradient line
        self.set_fill_color(*ACCENT_INDIGO)
        self.rect(0, 14, 105, 1, "F")
        self.set_fill_color(*ACCENT_CYAN)
        self.rect(105, 14, 105, 1, "F")
        # Title
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*TEXT_SECONDARY)
        self.set_xy(8, 3)
        self.cell(0, 8, "SpoofyVibe Executive Report", align="L")
        # Page number
        self.set_xy(-40, 3)
        self.cell(30, 8, f"Page {self.page_no()}", align="R")
        self.set_y(20)

    def footer(self):
        """Footer with timestamp."""
        if self.page_no() == 1:
            return
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 8, f"Generated by SpoofyVibe  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

    # ── Drawing helpers ─────────────────────────────────────────────────────

    def _section_title(self, title, y_pad=6):
        """Draw a section title with accent underline."""
        self.ln(y_pad)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*TEXT_PRIMARY)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        # Accent line
        x = self.get_x()
        y = self.get_y()
        self.set_fill_color(*ACCENT_INDIGO)
        self.rect(x, y, 40, 0.8, "F")
        self.set_fill_color(*ACCENT_CYAN)
        self.rect(x + 40, y, 40, 0.8, "F")
        self.ln(4)

    def _card_start(self, h=None):
        """Start a rounded card background."""
        self._card_x = self.get_x()
        self._card_y = self.get_y()
        return self._card_y

    def _card_end(self, start_y):
        """Draw card background behind content."""
        h = self.get_y() - start_y + 4
        x = 15
        w = 180
        self.set_fill_color(*CARD_BG)
        # Save current position, draw behind, restore
        cur_y = self.get_y()
        self.rect(x, start_y - 2, w, h, "F")
        self.set_y(cur_y + 2)

    def _score_bar(self, x, y, w, score, max_score, label):
        """Draw a score bar with label."""
        pct = score / max_score if max_score > 0 else 0
        bar_h = 5

        # Label
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*TEXT_SECONDARY)
        self.set_xy(x, y)
        self.cell(28, bar_h, label, align="L")

        bar_x = x + 30
        bar_w = w - 45

        # Background
        self.set_fill_color(40, 40, 60)
        self.rect(bar_x, y + 0.5, bar_w, bar_h - 1, "F")

        # Filled portion
        if pct >= 0.8:
            color = (16, 185, 129)
        elif pct >= 0.5:
            color = (234, 179, 8)
        else:
            color = (239, 68, 68)
        fill_w = bar_w * pct
        if fill_w > 0.5:
            self.set_fill_color(*color)
            self.rect(bar_x, y + 0.5, fill_w, bar_h - 1, "F")

        # Score text
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*TEXT_PRIMARY)
        self.set_xy(bar_x + bar_w + 2, y)
        self.cell(12, bar_h, f"{score}/{max_score}", align="R")

    def _grade_badge(self, x, y, grade, size=14):
        """Draw a circular grade badge."""
        color = GRADE_COLORS.get(grade, GRADE_COLORS["?"])
        r = size / 2
        cx, cy = x + r, y + r

        # Circle
        self.set_fill_color(*color)
        # Draw as a filled ellipse
        self.ellipse(x, y, size, size, "F")

        # Grade text
        self.set_font("Helvetica", "B", int(size * 0.55))
        self.set_text_color(255, 255, 255)
        tw = self.get_string_width(grade)
        self.set_xy(cx - tw / 2, cy - size * 0.22)
        self.cell(tw, size * 0.45, grade)


def generate_pdf_report(results, filename="spoofyvibe_report.pdf"):
    """
    Generate a boardroom-ready PDF executive report.

    Args:
        results: list of result dicts from process_domain()
        filename: output file path

    Returns:
        str: the output filename
    """
    pdf = PDFReport()

    # ── Page 1: Cover ────────────────────────────────────────────────────

    pdf.add_page()
    pdf.set_fill_color(*DARK_BG)
    pdf.rect(0, 0, 210, 297, "F")

    # Accent bar at top
    pdf.set_fill_color(*ACCENT_INDIGO)
    pdf.rect(0, 0, 210, 4, "F")
    pdf.set_fill_color(*ACCENT_CYAN)
    pdf.rect(0, 4, 210, 2, "F")

    # Title block
    pdf.set_y(80)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*ACCENT_CYAN)
    pdf.cell(0, 16, "SpoofyVibe", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*TEXT_PRIMARY)
    pdf.cell(0, 10, "Email Security Executive Report", align="C", new_x="LMARGIN", new_y="NEXT")

    # Divider
    pdf.ln(8)
    pdf.set_fill_color(*ACCENT_INDIGO)
    pdf.rect(60, pdf.get_y(), 35, 0.8, "F")
    pdf.set_fill_color(*ACCENT_CYAN)
    pdf.rect(95, pdf.get_y(), 55, 0.8, "F")
    pdf.ln(12)

    # Scan metadata
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*TEXT_SECONDARY)

    domain_count = len(results)
    scan_date = datetime.now().strftime("%B %d, %Y at %H:%M")
    domains_list = ", ".join(r.get("DOMAIN", "?") for r in results[:5])
    if domain_count > 5:
        domains_list += f" (+{domain_count - 5} more)"

    meta_items = [
        f"Scan Date:  {scan_date}",
        f"Domains Analyzed:  {domain_count}",
        f"Targets:  {domains_list}",
    ]

    for item in meta_items:
        pdf.cell(0, 8, item, align="C", new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.set_y(260)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*TEXT_MUTED)
    pdf.cell(0, 6, _safe("Generated by SpoofyVibe - github.com/fd/SpoofyVibe"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _safe("Confidential - For authorized recipients only"), align="C")

    # ── Page 2: Executive Summary ────────────────────────────────────────

    pdf.add_page()
    pdf.set_fill_color(*DARK_BG)
    pdf.rect(0, 0, 210, 297, "F")

    pdf._section_title("Executive Summary")

    # Key stats
    scores = [r.get("SECURITY_SCORE", 0) for r in results]
    grades = [r.get("SECURITY_GRADE", "?") for r in results]
    avg_score = sum(scores) / len(scores) if scores else 0
    spoofable_count = sum(1 for r in results if r.get("SPOOFING_POSSIBLE"))
    critical_count = sum(
        1 for r in results
        for rec in r.get("RECOMMENDATIONS", [])
        if rec.get("priority", 5) == 1
    )

    # Stats cards
    stat_items = [
        ("Average Score", f"{avg_score:.0f} / 100"),
        ("Domains Scanned", str(domain_count)),
        ("Spoofable Domains", str(spoofable_count)),
        ("Critical Issues", str(critical_count)),
    ]

    card_w = 42
    start_x = 15
    y = pdf.get_y() + 2

    for i, (label, value) in enumerate(stat_items):
        x = start_x + i * (card_w + 2.5)
        pdf.set_fill_color(*CARD_BG)
        pdf.rect(x, y, card_w, 22, "F")
        # Value
        pdf.set_font("Helvetica", "B", 16)
        if "Spoofable" in label and spoofable_count > 0:
            pdf.set_text_color(239, 68, 68)
        elif "Critical" in label and critical_count > 0:
            pdf.set_text_color(249, 115, 22)
        else:
            pdf.set_text_color(*ACCENT_CYAN)
        pdf.set_xy(x + 2, y + 2)
        pdf.cell(card_w - 4, 10, value, align="C")
        # Label
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.set_xy(x + 2, y + 13)
        pdf.cell(card_w - 4, 6, label, align="C")

    pdf.set_y(y + 28)

    # Grade distribution
    pdf._section_title("Grade Distribution", y_pad=4)

    grade_counts = {}
    for g in grades:
        grade_counts[g] = grade_counts.get(g, 0) + 1

    y = pdf.get_y() + 2
    grade_order = ["A+", "A", "B+", "B", "C+", "C", "D", "F"]
    bar_max_w = 100
    bar_h = 7

    for grade in grade_order:
        count = grade_counts.get(grade, 0)
        if count == 0:
            continue
        color = GRADE_COLORS.get(grade, GRADE_COLORS["?"])

        # Grade label
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*color)
        pdf.set_xy(20, y)
        pdf.cell(12, bar_h, grade, align="C")

        # Bar
        pct = count / domain_count if domain_count > 0 else 0
        fill_w = max(bar_max_w * pct, 2)
        pdf.set_fill_color(*color)
        pdf.rect(35, y + 1, fill_w, bar_h - 2, "F")

        # Count
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*TEXT_PRIMARY)
        pdf.set_xy(35 + fill_w + 3, y)
        pdf.cell(20, bar_h, f"{count} domain{'s' if count != 1 else ''}")

        y += bar_h + 2

    pdf.set_y(y + 4)

    # ── Per-domain score breakdowns ──────────────────────────────────────

    pdf._section_title("Domain Score Breakdown")

    for result in results:
        domain = result.get("DOMAIN", "unknown")
        score = result.get("SECURITY_SCORE", 0)
        grade = result.get("SECURITY_GRADE", "?")
        breakdown = result.get("SCORE_BREAKDOWN", {})
        spoofable = result.get("SPOOFING_POSSIBLE")

        # Check if we need a new page (leave room for bars)
        if pdf.get_y() > 210:
            pdf.add_page()
            pdf.set_fill_color(*DARK_BG)
            pdf.rect(0, 0, 210, 297, "F")
            pdf._section_title("Domain Score Breakdown (continued)")

        y = pdf.get_y()

        # Card background
        card_h = 8 + len(CATEGORY_LABELS) * 7 + 4
        pdf.set_fill_color(*CARD_BG)
        pdf.rect(15, y, 180, card_h, "F")

        # Grade badge
        pdf._grade_badge(18, y + 3, grade, size=12)

        # Domain name
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*TEXT_PRIMARY)
        pdf.set_xy(34, y + 2)
        pdf.cell(80, 6, domain)

        # Score
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.set_xy(34, y + 8)
        spoof_txt = ""
        if spoofable is True:
            spoof_txt = "  |  Spoofable"
            pdf.set_text_color(239, 68, 68)
        elif spoofable is False:
            spoof_txt = "  |  Not Spoofable"
        pdf.cell(80, 5, _safe(f"Score: {score}/100{spoof_txt}"))

        # Score bars
        bar_y = y + 16
        for key, label, max_pts in CATEGORY_LABELS:
            raw = breakdown.get(key, 0)
            # Handle both dict ({score, max, percentage}) and int values
            if isinstance(raw, dict):
                cat_score = raw.get("score", 0)
                max_pts = raw.get("max", max_pts)
            else:
                cat_score = raw if isinstance(raw, (int, float)) else 0
            pdf._score_bar(20, bar_y, 170, cat_score, max_pts, label)
            bar_y += 7

        pdf.set_y(y + card_h + 4)

    # ── Domain Details ───────────────────────────────────────────────────

    pdf.add_page()
    pdf.set_fill_color(*DARK_BG)
    pdf.rect(0, 0, 210, 297, "F")
    pdf._section_title("Domain Details")

    for result in results:
        domain = result.get("DOMAIN", "unknown")
        grade = result.get("SECURITY_GRADE", "?")

        if pdf.get_y() > 210:
            pdf.add_page()
            pdf.set_fill_color(*DARK_BG)
            pdf.rect(0, 0, 210, 297, "F")
            pdf._section_title("Domain Details (continued)")

        y = pdf.get_y()

        # Domain header
        pdf.set_font("Helvetica", "B", 10)
        color = GRADE_COLORS.get(grade, GRADE_COLORS["?"])
        pdf.set_text_color(*color)
        pdf.cell(0, 7, _safe(f"{grade}  {domain}"), new_x="LMARGIN", new_y="NEXT")

        # Detail rows
        details = _extract_details(result)
        pdf.set_font("Helvetica", "", 8)

        for label, value in details:
            if pdf.get_y() > 270:
                pdf.add_page()
                pdf.set_fill_color(*DARK_BG)
                pdf.rect(0, 0, 210, 297, "F")
                pdf._section_title("Domain Details (continued)")

            pdf.set_text_color(*TEXT_SECONDARY)
            x = pdf.get_x()
            y_row = pdf.get_y()
            pdf.set_xy(x, y_row)
            pdf.cell(38, 5, _safe(label), align="L")
            pdf.set_text_color(*TEXT_PRIMARY)
            # Truncate long values
            if len(value) > 110:
                value = value[:107] + "..."
            pdf.multi_cell(140, 5, _safe(value), new_x="LMARGIN", new_y="NEXT")

        # Separator
        pdf.set_draw_color(*BORDER_COLOR)
        pdf.line(15, pdf.get_y() + 1, 195, pdf.get_y() + 1)
        pdf.ln(4)

    # ── Remediation ──────────────────────────────────────────────────────

    all_recs = []
    for result in results:
        domain = result.get("DOMAIN", "unknown")
        for rec in result.get("RECOMMENDATIONS", []):
            rec_copy = dict(rec)
            rec_copy["_domain"] = domain
            all_recs.append(rec_copy)

    # Sort by priority
    all_recs.sort(key=lambda r: r.get("priority", 5))

    if all_recs:
        pdf.add_page()
        pdf.set_fill_color(*DARK_BG)
        pdf.rect(0, 0, 210, 297, "F")
        pdf._section_title(f"Remediation Recommendations ({len(all_recs)} items)")

        for rec in all_recs:
            pri = rec.get("priority", 5)
            pri_label = PRIORITY_LABELS.get(pri, "INFO")
            pri_color = PRIORITY_COLORS.get(pri, PRIORITY_COLORS[5])
            domain = rec.get("_domain", "")
            title = rec.get("title", "")
            desc = rec.get("description", "")
            fix = rec.get("fix", "")

            if pdf.get_y() > 240:
                pdf.add_page()
                pdf.set_fill_color(*DARK_BG)
                pdf.rect(0, 0, 210, 297, "F")
                pdf._section_title("Remediation (continued)")

            y = pdf.get_y()

            # Priority badge
            pdf.set_fill_color(*pri_color)
            badge_w = pdf.get_string_width(pri_label) + 6
            pdf.rect(15, y, badge_w + 2, 5.5, "F")
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(255, 255, 255)
            pdf.set_xy(16, y + 0.5)
            pdf.cell(badge_w, 4.5, pri_label)

            # Category + domain
            cat = rec.get("category", "")
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*TEXT_MUTED)
            pdf.set_xy(16 + badge_w + 4, y + 0.5)
            pdf.cell(60, 4.5, _safe(f"{cat}  *  {domain}"))

            pdf.ln(7)

            # Title
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*TEXT_PRIMARY)
            pdf.cell(0, 5, _safe(title), new_x="LMARGIN", new_y="NEXT")

            # Description
            if desc:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*TEXT_SECONDARY)
                pdf.multi_cell(180, 4.5, _safe(desc), new_x="LMARGIN", new_y="NEXT")

            # Fix
            if fix:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*ACCENT_CYAN)
                pdf.multi_cell(180, 4.5, _safe(f"Fix: {fix}"), new_x="LMARGIN", new_y="NEXT")

            pdf.ln(3)

    # ── Write file ───────────────────────────────────────────────────────

    pdf.output(filename)
    return filename


def _extract_details(result):
    """Extract key detail rows from a scan result."""
    details = []

    # SPF
    spf = result.get("SPF")
    if spf:
        details.append(("SPF Record", spf[:200]))
    else:
        details.append(("SPF Record", "Not found"))

    # DMARC
    dmarc = result.get("DMARC")
    if dmarc:
        details.append(("DMARC Record", dmarc[:200]))
    else:
        details.append(("DMARC Record", "Not found"))

    # DKIM
    dkim_count = result.get("DKIM_SELECTOR_COUNT", 0)
    if dkim_count > 0:
        selectors = result.get("DKIM_SELECTORS", [])
        sel_names = [s.get("selector", "?") for s in selectors[:6]]
        weak_count = sum(1 for s in selectors if s.get("is_weak"))
        txt = f"{dkim_count} selectors: {', '.join(sel_names)}"
        if weak_count > 0:
            txt += f" ({weak_count} weak)"
        details.append(("DKIM", txt))
    else:
        details.append(("DKIM", "No selectors found"))

    # BIMI
    bimi = result.get("BIMI")
    details.append(("BIMI", bimi if bimi else "Not found"))

    # MTA-STS
    mta_mode = result.get("MTASTS_MODE")
    details.append(("MTA-STS", mta_mode if mta_mode else "Not configured"))

    # MX
    mx_records = result.get("MX_RECORDS", [])
    if mx_records:
        mx_list = [f"{m.get('host', '?')} (pri {m.get('priority', '?')})" for m in mx_records[:4]]
        details.append(("MX Hosts", ", ".join(mx_list)))

    # DNSSEC
    dnssec = result.get("DNSSEC_ENABLED", False)
    ds = result.get("DNSSEC_HAS_DS", False)
    dnssec_txt = "Enabled" if dnssec else "Not enabled"
    if ds:
        dnssec_txt += " - DS verified"
    details.append(("DNSSEC", dnssec_txt))

    # DANE
    dane = result.get("DANE_HAS_TLSA", False)
    dane_mx = result.get("DANE_MX_COUNT", 0)
    dane_total = result.get("DANE_TOTAL_MX", 0)
    if dane:
        details.append(("DANE/TLSA", f"{dane_mx}/{dane_total} MX hosts covered"))
    else:
        details.append(("DANE/TLSA", "No TLSA records"))

    # M365
    if result.get("M365_DETECTED"):
        tenant = result.get("M365_TENANT_NAME", "Unknown")
        details.append(("Microsoft 365", f"Tenant: {tenant}"))

    return details
